<!-- This is Navbar code written in Svelte  -->

<script>
    // None of the code is Generated by Large Language Models like ChatGPT.
    // Detailed comments exists for CSS and unusual HTML 
    

</script>

<nav id="nav">
    <ul class="first-half">
        <li>
            <a href="/">
                <img src="/logo.png" alt="Main logo" />
            </a>
        </li>
    </ul>
    <ul class="second-half">
        <li><a href="/product">Product Master</a></li>
        <li><a href="/additems">Add Items</a></li>
        <li><a href="/removeitems">Remove Items</a></li>
        <li><a href="/inwards">Inwards</a><li>
        <li><a href="/outwards">Outwards</a></li>
    </ul>
</nav>

<style>
    /* 
      Sticky, semi-transparent nav with a subtle gradient background.
      - The gradient adds depth without distracting from the content.
      - The color scheme is neutral, but you can swap in brand colors easily.
    */
    /* Basic reset / normalization (optional but recommended) */
    * {
        margin: 0;
        padding: 0;
    }
    /* NAV WRAPPER */
    nav#nav {
        display: flex;                 /* Use Flexbox for positioning */
        justify-content: space-between;
        align-items: center;
        background-color: #ffffff;     /* Light background color */
        padding: 0.5rem 1rem;         /* Adjust spacing around nav */
        box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1); /* Subtle drop shadow */
    }

    /* UL (FIRST-HALF & SECOND-HALF) */
    nav#nav ul {
        list-style: none;              /* Remove default bullet points */
        display: flex;                 /* Align items horizontally */
        gap: 1rem;                     /* Space out list items */
    }

    /* LOGO AREA */
    nav#nav .first-half li a {
        display: flex;                 /* So the logo area is clickable as a whole */
        align-items: center;
    }

    nav#nav .first-half img {
        height: 40px;                  /* Adjust as needed */
        width: auto;
        vertical-align: middle;
    }

    /* LINK STYLING */
    nav#nav ul.second-half li a {
        color: #333;                   /* Text color */
        text-decoration: none;
        font-weight: 500;
        padding: 0.5rem 0.75rem;       /* Inner spacing around each link */
        border-radius: 4px;            /* Slightly rounded corners */
        transition: background-color 1s, color 1s; /* Please find the hover CSS below */
    }
 
    nav#nav ul.second-half li a:hover {
        background-color: #6c3737;        /* Hover background */
        color: #f1e75d;                   /* Hover text color */
    }

    /* RESPONSIVENESS / MEDIA QUERIES */
    @media (max-width: 600px) {
    nav#nav {
        flex-direction: column;      /* Stack the logo and links vertically */
        align-items: flex-start;
    }

    nav#nav ul {
        flex-direction: column;      /* Vertically stacked links */
        width: 100%;                 /* Full width for each list */
    }

    nav#nav ul.second-half li a {
        width: 100%;                 /* Make links full-width on small screens */
    }
    }
    

  </style>
